name: Run Python Script

on:
  schedule:
    - cron: '14,16,22 * * *'  # Runs at 14:00, 16:00, and 22:00 UTC every day

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # Specify your Python version (e.g., 3.8, 3.9, etc.)

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 4: Run the Python script
    - name: Run Python script
      run: DataFeedFromYahoo.py